# Generated by Django 4.2.23 on 2025-06-22 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalibrationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calibration_date', models.DateField()),
                ('calibrated_by', models.CharField(max_length=100)),
                ('expires_on', models.DateField()),
                ('comments', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('organization', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('token', models.CharField(max_length=20, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ControlSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_acceptable', models.DecimalField(decimal_places=4, max_digits=8)),
                ('max_acceptable', models.DecimalField(decimal_places=4, max_digits=8)),
                ('unit', models.CharField(default='%', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(choices=[('Balance', 'Balance'), ('Oven', 'Oven'), ('Spectrometer', 'Spectrometer')], max_length=50)),
                ('date_installed', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=20)),
                ('method', models.CharField(max_length=150)),
                ('ref_limit', models.CharField(max_length=50)),
                ('default_price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='ParameterGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_extension', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='QCMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_value', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('tolerance', models.DecimalField(decimal_places=2, default=10.0, help_text='±% allowed deviation', max_digits=5)),
                ('min_acceptable', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('max_acceptable', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('measured_value', models.DecimalField(decimal_places=2, max_digits=8)),
                ('recovery_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('status', models.CharField(blank=True, choices=[('pass', 'Pass'), ('fail', 'Fail')], max_length=10)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='QCMetricsHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measured_value', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_code', models.CharField(max_length=50, unique=True)),
                ('sample_type', models.CharField(max_length=100)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('humidity', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('status', models.CharField(choices=[('received', 'Received'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='received', max_length=20)),
                ('received_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('is_control', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TestEnvironment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('humidity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pressure', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('system', 'System')], default='manual', max_length=20)),
                ('calculation_note', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
