# Generated by Django 4.2.23 on 2025-06-22 20:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lims', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='recorded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='testresult',
            name='test_assignment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lims.testassignment'),
        ),
        migrations.AddField(
            model_name='testenvironment',
            name='instrument',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lims.equipment'),
        ),
        migrations.AddField(
            model_name='testenvironment',
            name='recorded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='testenvironment',
            name='test_assignment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lims.testassignment'),
        ),
        migrations.AddField(
            model_name='testassignment',
            name='analyst',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='testassignment',
            name='equipment_used',
            field=models.ForeignKey(blank=True, help_text='Equipment used for this test', null=True, on_delete=django.db.models.deletion.SET_NULL, to='lims.equipment'),
        ),
        migrations.AddField(
            model_name='testassignment',
            name='parameter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lims.parameter'),
        ),
        migrations.AddField(
            model_name='testassignment',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lims.sample'),
        ),
        migrations.AddField(
            model_name='sample',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lims.client'),
        ),
        migrations.AddField(
            model_name='qcmetricshistory',
            name='analyst',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='qcmetricshistory',
            name='qc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='lims.qcmetrics'),
        ),
        migrations.AddField(
            model_name='qcmetrics',
            name='test_assignment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qc_metrics', to='lims.testassignment'),
        ),
        migrations.AddField(
            model_name='parameter',
            name='default_equipment',
            field=models.ForeignKey(blank=True, help_text='Preferred device for this test', null=True, on_delete=django.db.models.deletion.SET_NULL, to='lims.equipment'),
        ),
        migrations.AddField(
            model_name='parameter',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lims.parametergroup'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='parameters_supported',
            field=models.ManyToManyField(blank=True, to='lims.parameter'),
        ),
        migrations.AddField(
            model_name='controlspec',
            name='parameter',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='control_spec', to='lims.parameter'),
        ),
        migrations.AddField(
            model_name='calibrationrecord',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calibrations', to='lims.equipment'),
        ),
    ]
