# Generated by Django 4.2.23 on 2025-06-23 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0003_alter_client_token_alter_equipment_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qcmetrics',
            name='measured_value',
            field=models.DecimalField(decimal_places=2, max_digits=8, null='True'),
        ),
    ]
