# Generated by Django 4.2.23 on 2025-06-23 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0004_alter_qcmetrics_measured_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlspec',
            name='default_tolerance',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='±% allowed deviation', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='controlspec',
            name='expected_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
