from django.core.management.base import BaseCommand
from lims.models import Reagent  

class Command(BaseCommand):
    help = "Seeds all 2025 chemical reagents into the database"

    def handle(self, *args, **kwargs):
        reagents = [
            Reagent(name="ACETONE/Liter", number_of_containers=1, quantity_per_container=1),
            Reagent(name="ACETONITIRATE HPLC GRADE", number_of_containers=2, quantity_per_container=1),
            Reagent(name="ALANINE", number_of_containers=1, quantity_per_container=1),
            Reagent(name="ALBUMIN", number_of_containers=0, quantity_per_container=1),
            Reagent(name="ALUMINIUM CHLORIDE", number_of_containers=0, quantity_per_container=1),
            Reagent(name="ALUTAMINE", number_of_containers=0, quantity_per_container=1),
            Reagent(name="AMMONIUM CHLORIDE", number_of_containers=1, quantity_per_container=1),
            Reagent(name="AMMONIA SOLUTION", number_of_containers=1, quantity_per_container=1),
            Reagent(name="AMMONIUM FERROUS", number_of_containers=0, quantity_per_container=1),
            Reagent(name="AMMONIUM HEPTAMOLYBDATE", number_of_containers=0, quantity_per_container=1),
            Reagent(name="AMMONIUM HYDROXIDE(2.5L)", number_of_containers=0, quantity_per_container=1),
            Reagent(name="AMMONIUM METAVANADATE(300g)", number_of_containers=0, quantity_per_container=1),
            Reagent(name="AMMONIUM MOLYBDATE", number_of_containers=1, quantity_per_container=1),
            Reagent(name="AMMONIUM MONOVANADATE", number_of_containers=0, quantity_per_container=1),
            Reagent(name="AMMONIUM SULFATE", number_of_containers=0, quantity_per_container=1),
            Reagent(name="AMMONIUM THIOCYNANATE", number_of_containers=0, quantity_per_container=1),
            Reagent(name="ANILINE", number_of_containers=1, quantity_per_container=1),
            Reagent(name="ANTHRONE(4g)", number_of_containers=0, quantity_per_container=1),
            Reagent(name="ARGININE", number_of_containers=0, quantity_per_container=1),
            Reagent(name="ASCORBIC ACID", number_of_containers=0, quantity_per_container=1),
            Reagent(name="ASPARAGINE", number_of_containers=1, quantity_per_container=1),
            Reagent(name="BARIUM CHLORIDE", number_of_containers=0, quantity_per_container=1),
            Reagent(name="BARIUM NITRATE", number_of_containers=0, quantity_per_container=1),
            Reagent(name="BENZENE", number_of_containers=0, quantity_per_container=1),
            Reagent(name="BORIC ACID 500g", number_of_containers=3, quantity_per_container=1),
            Reagent(name="BROMOCRESOL GREEN", number_of_containers=1, quantity_per_container=1),
            Reagent(name="CACIUM CARBONATE", number_of_containers=0, quantity_per_container=1),
            Reagent(name="CAESIUM CHLORIDE )", number_of_containers=0, quantity_per_container=1),
            Reagent(name="CASEIN PROTEIN RICH", number_of_containers=0, quantity_per_container=1),
            Reagent(name="CELITE 545(20g)", number_of_containers=0, quantity_per_container=1),
            Reagent(name="CHLOROFOAM(2.5L)", number_of_containers=2, quantity_per_container=1),
            Reagent(name="CTAB 100g", number_of_containers=0, quantity_per_container=1),
            Reagent(name="DICHLOROMENTHANE", number_of_containers=0, quantity_per_container=1),
            Reagent(name="DIETHYL ETHER", number_of_containers=2, quantity_per_container=1),
            Reagent(name="DIETHYLENE GLYCOL(2.5l)", number_of_containers=0, quantity_per_container=1),
            Reagent(name="DI-POTASSIUM HYDROGEN ORTHOPHOSPHATE", number_of_containers=0, quantity_per_container=1),
            Reagent(name="DISODIUM HYDROGEN OTHOPHOSPHATE", number_of_containers=0, quantity_per_container=1),
            Reagent(name="DI-SODIUM TETRABORATE", number_of_containers=0, quantity_per_container=1),
            Reagent(name="EDTA (500g)", number_of_containers=0, quantity_per_container=1),
            Reagent(name="EHANEDIOL", number_of_containers=1, quantity_per_container=1),
            Reagent(name="ERICHROME BLACK T INDICATOR", number_of_containers=0, quantity_per_container=1),
            Reagent(name="ETHANOL 2.5L", number_of_containers=0, quantity_per_container=1),
            Reagent(name="FERRIC CHLORIDE", number_of_containers=1, quantity_per_container=1),
            Reagent(name="FOMIC ACID", number_of_containers=1, quantity_per_container=1),
            Reagent(name="GLUTAMIC ACID", number_of_containers=1, quantity_per_container=1),
            Reagent(name="GLYCINE", number_of_containers=1, quantity_per_container=1),
            Reagent(name="HISTIDINE MONOHYDROCHLORIDE MONOHYDRATE", number_of_containers=1, quantity_per_container=1),
            Reagent(name="HYDROCHLORIC ACID 2.5L", number_of_containers=3, quantity_per_container=1),
            Reagent(name="ISOPROPYL ALCOHOL", number_of_containers=1, quantity_per_container=1),
            Reagent(name="L-ASCORBIC ACID", number_of_containers=2, quantity_per_container=1),
            Reagent(name="L-ASPARTIC", number_of_containers=1, quantity_per_container=1),
            Reagent(name="LEUCINE", number_of_containers=1, quantity_per_container=1),
            Reagent(name="L-ISOLEUCINE", number_of_containers=1, quantity_per_container=1),
            Reagent(name="L-PROLINE", number_of_containers=1, quantity_per_container=1),
            Reagent(name="LYSINE MONOCHLORIDE", number_of_containers=1, quantity_per_container=1),
            Reagent(name="MAGNESIUM CHLORIDE", number_of_containers=0, quantity_per_container=1),
            Reagent(name="METHANOL", number_of_containers=2, quantity_per_container=1),
            Reagent(name="METHIONINE", number_of_containers=1, quantity_per_container=1),
            Reagent(name="NINHYDRIN", number_of_containers=1, quantity_per_container=1),
            Reagent(name="NITRIC ACID 2.5L", number_of_containers=3, quantity_per_container=1),
            Reagent(name="N-OCTANOL", number_of_containers=1, quantity_per_container=1),
            Reagent(name="PEPSIN", number_of_containers=0, quantity_per_container=1),
            Reagent(name="PETROLEUM SPIRIT 2.5L", number_of_containers=6, quantity_per_container=1),
            Reagent(name="PHENANTHROLINE", number_of_containers=0, quantity_per_container=1),
            Reagent(name="PHENOLPHETALEIN (20g)", number_of_containers=1, quantity_per_container=1),
            Reagent(name="POLYVINYLPYRROLIDONE", number_of_containers=1, quantity_per_container=1),
            Reagent(name="POTASSIUM DIHYDROGEN PHOSPHATE", number_of_containers=0, quantity_per_container=1),
            Reagent(name="POTASSIUM HYDROXIDE", number_of_containers=1, quantity_per_container=1),
            Reagent(name="POTASSIUM SODIUM TARTRATE (500g)", number_of_containers=0, quantity_per_container=1),
            Reagent(name="POTTASIUM IODATE", number_of_containers=0, quantity_per_container=1),
            Reagent(name="RETINYL PALMITATE (VITAMIN A)", number_of_containers=0, quantity_per_container=1),
            Reagent(name="SAPONIN STANDARD", number_of_containers=0, quantity_per_container=1),
            Reagent(name="SERIN", number_of_containers=0, quantity_per_container=1),
            Reagent(name="SILICA GEL", number_of_containers=2, quantity_per_container=1),
            Reagent(name="SILVER NITRATE", number_of_containers=0, quantity_per_container=1),
            Reagent(name="SODIUM CHLORIDE", number_of_containers=2, quantity_per_container=1),
            Reagent(name="SODIUM DIHYDROGEN PHOSPHATE", number_of_containers=1, quantity_per_container=1),
            Reagent(name="SODIUM HYDROXIDE 500g", number_of_containers=4, quantity_per_container=1),
            Reagent(name="SODIUM LAURYL SULPHATE", number_of_containers=1, quantity_per_container=1),
            Reagent(name="SULPHOSALICYLIC ACID", number_of_containers=1, quantity_per_container=1),
            Reagent(name="SULPHURIC ACID 2.5L", number_of_containers=3, quantity_per_container=1),
            Reagent(name="TANNIC ACID", number_of_containers=0, quantity_per_container=1),
            Reagent(name="THERMAMYL ALFA AMYLASE", number_of_containers=0, quantity_per_container=1),
            Reagent(name="THREONINE", number_of_containers=1, quantity_per_container=1),
            Reagent(name="TRIMETHYL AMMONIUM BROMIDE", number_of_containers=0, quantity_per_container=1),
            Reagent(name="TRYPTOPHAN", number_of_containers=0, quantity_per_container=1),
            Reagent(name="TYROSINE", number_of_containers=1, quantity_per_container=1),
            Reagent(name="VALINE", number_of_containers=1, quantity_per_container=1),
            Reagent(name="VANILLINE REAGENT", number_of_containers=0, quantity_per_container=1),
        ]

        Reagent.objects.bulk_create(reagents)
        self.stdout.write(self.style.SUCCESS(f"✅ Seeded {len(reagents)} reagents with quantity_per_container=1"))
